function run_device_tol()
% Read an impedance measurement and evaluate the tolerances.
%
%    Read a file generated by a HP/Agilent/Keysight 4294A impedance analyzer.
%    Extract the measurement tolerances.
%    Plot the measured values and the tolerances.
%
%    For the example, a resistive-inductive load is considered.
%
%    (c) 2016-2020, ETH Zurich, Power Electronic Systems Laboratory, T. Guillod

close('all')
addpath('utils')

%% param
BW = 5; % bandwidth setting of the impedance analyzer
V_osc = 500e-3; % oscillator voltage of the impedance analyzer

%% get the ranges
f_vec = logspace(log10(100.0), log10(100e6), 100);
Z_vec = logspace(log10(10e-3), log10(100e6), 100);
err_vec = logspace(log10(0.01), log10(10.0), 100);
[f_mat, Z_mat] = meshgrid(f_vec, Z_vec);

%% compute the device tolerances
[tol_abs, tol_rad, is_valid] = tolerance_4294A(f_mat, Z_mat, V_osc, BW);
assert(all(all(is_valid==true)), 'invalid data (outside the ranges definied in the datasheet)')

%% plot device tolerances
figure()

subplot(2,1,1)
contourf(f_vec, Z_vec, 100.0.*tol_abs, err_vec, 'Edgecolor', 'none')
hold('on')
set(gca, 'xscale', 'log')
set(gca, 'yscale', 'log')
set(gca,'ColorScale','log')
grid('on')
clim([0.1 10.0])
c = colorbar();
grid('on')
xlabel('f [Hz]')
ylabel('Z [Ohm]')
set(c.Label, 'String', 'Abs. Tol. [%]')
title('Tolerance / Absolute')

subplot(2,1,2)
contourf(f_vec, Z_vec, rad2deg(tol_rad), err_vec, 'Edgecolor', 'none')
hold('on')
set(gca, 'xscale', 'log')
set(gca, 'yscale', 'log')
set(gca,'ColorScale','log')
grid('on')
clim([0.1 10.0])
c = colorbar();
xlabel('f [Hz]')
ylabel('Z [Ohm]')
set(c.Label, 'String', 'Angle Tol. [deg]')
title('Tolerance / Angle')

end